services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-api
    ports:
      - "9051:9051"
    restart: always

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:9051
    container_name: react-web
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

networks:
  default:
    name: project-network
